# Generated by Django 5.2 on 2026-03-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код вида измерения')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop', models.IntegerField(verbose_name='Цех')),
                ('brigade', models.IntegerField(blank=True, null=True, verbose_name='Бригада')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='MocGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='Вид измерения')),
                ('group', models.IntegerField(blank=True, default=0, null=True, verbose_name='Группа СИ(код)')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Наименование группы СИ')),
            ],
        ),
        migrations.CreateModel(
            name='MocLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
                ('min_limit', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Мин. предел измерения')),
                ('max_limit', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Макс. предел измерения')),
                ('min_measurement', models.CharField(max_length=5, verbose_name='Единица изм. мин. предела')),
                ('max_measurement', models.CharField(max_length=5, verbose_name='Единица изм. макс. предела')),
            ],
        ),
        migrations.CreateModel(
            name='MocType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип СИ')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='Код')),
                ('accurancy', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Точность')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Стоимость госповерки')),
                ('min_limit', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Мин. предел измерения')),
                ('max_limit', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True, verbose_name='Макс. предел измерения')),
                ('min_measurement', models.CharField(blank=True, max_length=5, null=True, verbose_name='Единица изм. мин. предела')),
                ('max_measurement', models.CharField(blank=True, max_length=5, null=True, verbose_name='Единица изм. макс. предела')),
                ('standart_verification', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Норма поверки')),
                ('standart_repair', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Норма ремонта')),
                ('rank_verification', models.IntegerField(blank=True, null=True, verbose_name='Разряд поверителя')),
                ('rank_repair', models.IntegerField(blank=True, null=True, verbose_name='Разряд ремонтника')),
            ],
        ),
        migrations.CreateModel(
            name='PreciousMetals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='RepairCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='RepairDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('sign', models.IntegerField(verbose_name='Разряд')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('is_active', models.BooleanField(verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='UnitsMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Код')),
                ('sign', models.IntegerField(verbose_name='Признак')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_active', models.BooleanField(verbose_name='Активно')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('rank', models.IntegerField(verbose_name='Разряд')),
                ('fio', models.CharField(max_length=100, verbose_name='Фио')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
    ]
