# Generated by Django 5.2 on 2026-02-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop', models.IntegerField(verbose_name='workshop')),
                ('brigade', models.IntegerField(verbose_name='brigade')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='MocGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(verbose_name='Тип')),
                ('group', models.IntegerField(verbose_name='Группа')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='MocLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Код')),
                ('min_limit', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Мин. лимит')),
                ('max_limit', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Макс. лимит')),
                ('min_measurement', models.CharField(max_length=5, verbose_name='Мин. измерение')),
                ('max_measurement', models.CharField(max_length=5, verbose_name='Макс. измерение')),
            ],
        ),
        migrations.CreateModel(
            name='MocType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
                ('code', models.IntegerField(verbose_name='Код')),
                ('accurancy', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Точность')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('min_limit', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Мин. лимит')),
                ('max_limit', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Макс. лимит')),
                ('min_measurement', models.CharField(max_length=5, verbose_name='Мин. измерение')),
                ('max_measurement', models.CharField(max_length=5, verbose_name='Макс. измерение')),
                ('standart_verification', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Стандарт поверки')),
                ('standart_repair', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Стандартный ремонт')),
                ('rank_verification', models.IntegerField(verbose_name='Разряд поверки')),
                ('rank_repair', models.IntegerField(verbose_name='Разряд ремонта')),
            ],
        ),
        migrations.CreateModel(
            name='PreciousMetals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='RepairCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='RepairDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Код')),
                ('sign', models.IntegerField(verbose_name='Знак')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_active', models.BooleanField(verbose_name='Активно')),
            ],
        ),
        migrations.CreateModel(
            name='UnitsMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Код')),
                ('sign', models.IntegerField(verbose_name='Знак')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_active', models.BooleanField(verbose_name='Активно')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Код')),
                ('rank', models.IntegerField(verbose_name='Разряд')),
                ('fio', models.CharField(max_length=100, verbose_name='Фио')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
    ]
