# Generated by Django 5.2 on 2026-03-18 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('handbooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_number', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Инвентарный номер')),
                ('station_inv_number', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Инвентарный номер оборудовния')),
                ('station_name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Название оборудования')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_number', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Инвентарный номер')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_location', to='handbooks.department')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceStatusDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_number', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Инвентарный номер')),
                ('status_date', models.DateField(blank=True, null=True, verbose_name='Дата статуса')),
                ('device_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_status_date', to='handbooks.devicestatus')),
            ],
        ),
        migrations.CreateModel(
            name='MocList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_number', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Заводской номер')),
                ('inv_number', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Инвентарный номер')),
                ('sign_o_r', models.CharField(choices=[('Р', 'Рабочий'), ('О', 'Образцовый')], default='Р', max_length=1, verbose_name='Признак')),
                ('sign_o_m', models.CharField(choices=[('О', 'Основной'), ('М', 'Малоценный')], default='М', max_length=1, verbose_name='Признак')),
                ('verification_period', models.IntegerField(blank=True, default=0, null=True, verbose_name='Период поверки(кол-во месяцев)')),
                ('verification_type', models.CharField(choices=[('Г', 'Государственная'), ('В', 'Ведомственная')], default='Г', max_length=1, verbose_name='Вид поверки')),
                ('change_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moc_list', to='handbooks.changetype')),
                ('moc_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moc_list', to='handbooks.mocgroup')),
                ('moc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moc_list', to='handbooks.moctype')),
                ('verification_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moc_list', to='handbooks.verificationdepartment')),
            ],
        ),
        migrations.CreateModel(
            name='MocMetals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_number', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Инвентарный номер')),
                ('metal_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Содержание металла')),
                ('precious_metals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moc_metals', to='handbooks.preciousmetals')),
            ],
        ),
        migrations.CreateModel(
            name='RepairInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_number', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Инвентарный номер')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('entry_repair_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи в ремонт')),
                ('repair_date', models.DateField(blank=True, null=True, verbose_name='Дата ремонта')),
                ('repair_type', models.CharField(choices=[('4', 'Текущий'), ('7', 'Долгосрочный')], default='4', max_length=1, verbose_name='Вид ремонта')),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_info', to='handbooks.repair')),
                ('repair_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_info', to='handbooks.repaircode')),
                ('repair_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_info', to='handbooks.repairdepartment')),
                ('verification_sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_info', to='handbooks.verificationsign')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_number', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Инвентарный номер')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='Дата поступления на поверку')),
                ('verification_date', models.DateField(blank=True, null=True, verbose_name='Дата поверки')),
                ('workshop_issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи в цех')),
                ('verification_result', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Результат поверки')),
                ('verification_document_num', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Номер документа о поверке')),
                ('verification_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_info', to='handbooks.verificationperson')),
                ('verification_sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_info', to='handbooks.verificationsign')),
            ],
        ),
    ]
