# Generated by Django 5.2 on 2026-03-20 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocmetals',
            name='moc_list',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='moc_metals', to='passport.moclist'),
            preserve_default=False,
        ),
    ]
