# Generated by Django 5.2 on 2026-03-20 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0002_mocmetals_moc_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelocation',
            name='moc_list',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='device_location', to='passport.moclist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicestation',
            name='moc_list',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='device_station', to='passport.moclist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicestatusdate',
            name='moc_list',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='device_status_date', to='passport.moclist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repairinfo',
            name='moc_list',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='repair_info', to='passport.moclist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verificationinfo',
            name='moc_list',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='verification_info', to='passport.moclist'),
            preserve_default=False,
        ),
    ]
