# Generated by Django 5.2 on 2026-04-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0003_devicelocation_moc_list_devicestation_moc_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moclist',
            name='sign_o_m',
            field=models.CharField(choices=[('О', 'Основной'), ('М', 'Малоценный'), ('В', 'Встроенный')], default='М', max_length=1, verbose_name='Признак'),
        ),
    ]
