# Generated by Django 5.2 on 2026-04-03 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbooks', '0001_initial'),
        ('passport', '0004_alter_moclist_sign_o_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationinfo',
            name='verification_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_info', to='handbooks.verificationperson'),
        ),
        migrations.AlterField(
            model_name='verificationinfo',
            name='verification_sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_info', to='handbooks.verificationsign'),
        ),
    ]
