# Generated by Django 5.2 on 2026-04-03 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbooks', '0001_initial'),
        ('passport', '0005_alter_verificationinfo_verification_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelocation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_location', to='handbooks.department'),
        ),
        migrations.AlterField(
            model_name='devicestatusdate',
            name='device_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_status_date', to='handbooks.devicestatus'),
        ),
        migrations.AlterField(
            model_name='repairinfo',
            name='repair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repair_info', to='handbooks.repair'),
        ),
        migrations.AlterField(
            model_name='repairinfo',
            name='repair_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repair_info', to='handbooks.repaircode'),
        ),
        migrations.AlterField(
            model_name='repairinfo',
            name='repair_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repair_info', to='handbooks.repairdepartment'),
        ),
        migrations.AlterField(
            model_name='repairinfo',
            name='verification_sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repair_info', to='handbooks.verificationsign'),
        ),
    ]
