# Generated by Django 5.2 on 2026-06-05 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbooks', '0001_initial'),
        ('passport', '0007_remove_repairinfo_verification_sign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moclist',
            name='change_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moc_list', to='handbooks.changetype'),
        ),
        migrations.AlterField(
            model_name='moclist',
            name='moc_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moc_list', to='handbooks.mocgroup'),
        ),
        migrations.AlterField(
            model_name='moclist',
            name='moc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moc_list', to='handbooks.moctype'),
        ),
        migrations.AlterField(
            model_name='moclist',
            name='verification_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moc_list', to='handbooks.verificationdepartment'),
        ),
        migrations.AlterField(
            model_name='mocmetals',
            name='precious_metals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moc_metals', to='handbooks.preciousmetals'),
        ),
    ]
