# Generated by Django 5.2 on 2026-06-05 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0008_alter_moclist_change_type_alter_moclist_moc_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelocation',
            name='moc_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_location', to='passport.moclist'),
        ),
        migrations.AlterField(
            model_name='devicestation',
            name='moc_list',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_station', to='passport.moclist'),
        ),
        migrations.AlterField(
            model_name='devicestatusdate',
            name='moc_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_status_date', to='passport.moclist'),
        ),
        migrations.AlterField(
            model_name='mocmetals',
            name='moc_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moc_metals', to='passport.moclist'),
        ),
        migrations.AlterField(
            model_name='repairinfo',
            name='moc_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repair_info', to='passport.moclist'),
        ),
        migrations.AlterField(
            model_name='verificationinfo',
            name='moc_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_info', to='passport.moclist'),
        ),
    ]
