# Generated by Django 5.2 on 2026-09-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0009_alter_devicelocation_moc_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moclist',
            name='sign_o_m',
            field=models.CharField(blank=True, choices=[('О', 'Основной'), ('М', 'Малоценный'), ('В', 'Встроенный')], default='М', max_length=1, null=True, verbose_name='Признак'),
        ),
        migrations.AlterField(
            model_name='moclist',
            name='sign_o_r',
            field=models.CharField(blank=True, choices=[('Р', 'Рабочий'), ('О', 'Образцовый')], default='Р', max_length=1, null=True, verbose_name='Признак'),
        ),
        migrations.AlterField(
            model_name='moclist',
            name='verification_type',
            field=models.CharField(blank=True, choices=[('Г', 'Государственная'), ('В', 'Ведомственная')], default='Г', max_length=1, null=True, verbose_name='Вид поверки'),
        ),
        migrations.AlterField(
            model_name='repairinfo',
            name='entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поступления в ремонт'),
        ),
        migrations.AlterField(
            model_name='repairinfo',
            name='repair_type',
            field=models.CharField(blank=True, choices=[('4', 'Текущий'), ('7', 'Долгосрочный')], default='4', max_length=1, null=True, verbose_name='Вид ремонта'),
        ),
    ]
