from django.urls import path
from . import views


urlpatterns = [
     # url paths for MocGroup
     path('moc_group/',
          views.MocGroupListView.as_view(),
          name='moc_group'),
     path('moc_group/add/',
          views.MocGroupAddView.as_view(),
          name='moc_group_add'),
     path('moc_group/<int:pk>/update/',
          views.MocGroupUpdateView.as_view(),
          name='moc_group_update'),
     path('moc_group/<int:pk>/delete/',
          views.MocGroupDeleteView.as_view(),
          name='moc_group_delete'),

     # url paths for ChangeType
     path('change_type/',
          views.ChangeTypeListView.as_view(),
          name='change_type'),
     path('change_type/add/',
          views.ChangeTypeAddView.as_view(),
          name='change_type_add'),
     path('change_type/<int:pk>/update/',
          views.ChangeTypeUpdateView.as_view(),
          name='change_type_update'),
     path('change_type/<int:pk>/delete/',
          views.ChangeTypeDeleteView.as_view(),
          name='change_type_delete'),

     # url paths for Department
     path('department/',
          views.DepartmentListView.as_view(),
          name='department'),
     path('department/add/',
          views.DepartmentAddView.as_view(),
          name='department_add'),
     path('department/<int:pk>/update/',
          views.DepartmentUpdateView.as_view(),
          name='department_update'),
     path('department/<int:pk>/delete/',
          views.DepartmentDeleteView.as_view(),
          name='department_delete'),

     # url paths for Repair
     path('repair/',
          views.RepairListView.as_view(),
          name='repair'),
     path('repair/add/',
          views.RepairAddView.as_view(),
          name='repair_add'),
     path('repair/<int:pk>/update/',
          views.RepairUpdateView.as_view(),
          name='repair_update'),
     path('repair/<int:pk>/delete/',
          views.RepairDeleteView.as_view(),
          name='repair_delete'),

     # url paths for PreciousMetals
     path('precious_metals/',
          views.PreciousMetalsListView.as_view(),
          name='precious_metals'),
     path('precious_metals/add/',
          views.PreciousMetalsAddView.as_view(),
          name='precious_metals_add'),
     path('precious_metals/<int:pk>/update/',
          views.PreciousMetalsUpdateView.as_view(),
          name='precious_metals_update'),
     path('precious_metals/<int:pk>/delete/',
          views.PreciousMetalsDeleteView.as_view(),
          name='precious_metals_delete'),

     # url paths for VerificationDepartment
     path('verification_department/',
          views.VerificationDepartmentListView.as_view(),
          name='verification_department'),
     path('verification_department/add/',
          views.VerificationDepartmentAddView.as_view(),
          name='verification_department_add'),
     path('verification_department/<int:pk>/update/',
          views.VerificationDepartmentUpdateView.as_view(),
          name='verification_department_update'),
     path('verification_department/<int:pk>/delete/',
          views.VerificationDepartmentDeleteView.as_view(),
          name='verification_department_delete'),

     # url paths for VerificationPerson
     path('verification_person/',
          views.VerificationPersonListView.as_view(),
          name='verification_person'),
     path('verification_person/add/',
          views.VerificationPersonAddView.as_view(),
          name='verification_person_add'),
     path('verification_person/<int:pk>/update/',
          views.VerificationPersonUpdateView.as_view(),
          name='verification_person_update'),
     path('verification_person/<int:pk>/delete/',
          views.VerificationPersonDeleteView.as_view(),
          name='verification_person_delete'),

     # url paths for RepairCode
     path('repair_code/',
          views.RepairCodeListView.as_view(),
          name='repair_code'),
     path('repair_code/add/',
          views.RepairCodeAddView.as_view(),
          name='repair_code_add'),
     path('repair_code/<int:pk>/update/',
          views.RepairCodeUpdateView.as_view(),
          name='repair_code_update'),
     path('repair_code/<int:pk>/delete/',
          views.RepairCodeDeleteView.as_view(),
          name='repair_code_delete'),

     # url paths for InstrumentFailure
     path('instrument_failure/',
          views.InstrumentFailureListView.as_view(),
          name='instrument_failure'),
     path('instrument_failure/add/',
          views.InstrumentFailureAddView.as_view(),
          name='instrument_failure_add'),
     path('instrument_failure/<int:pk>/update/',
          views.InstrumentFailureUpdateView.as_view(),
          name='instrument_failure_update'),
     path('instrument_failure/<int:pk>/delete/',
          views.InstrumentFailureDeleteView.as_view(),
          name='instrument_failure_delete'),

     # url paths for DeviceStatus
     path('device_status/',
          views.DeviceStatusListView.as_view(),
          name='device_status'),
     path('device_status/add/',
          views.DeviceStatusAddView.as_view(),
          name='device_status_add'),
     path('device_status/<int:pk>/update/',
          views.DeviceStatusUpdateView.as_view(),
          name='device_status_update'),
     path('device_status/<int:pk>/delete/',
          views.DeviceStatusDeleteView.as_view(),
          name='device_status_delete'),

     # url paths for MocType
     path('moc_type/',
          views.MocTypeListView.as_view(),
          name='moc_type'),
     path('moc_type/add/',
          views.MocTypeAddView.as_view(),
          name='moc_type_add'),
     path('moc_type/<int:pk>/update/',
          views.MocTypeUpdateView.as_view(),
          name='moc_type_update'),
     path('moc_type/<int:pk>/delete/',
          views.MocTypeDeleteView.as_view(),
          name='moc_type_delete'),

     # url paths for UnitsMeasurement
     path('units_measurement/',
          views.UnitsMeasurementListView.as_view(),
          name='units_measurement'),
     path('units_measurement/add/',
          views.UnitsMeasurementAddView.as_view(),
          name='units_measurement_add'),
     path('units_measurement/<int:pk>/update/',
          views.UnitsMeasurementUpdateView.as_view(),
          name='units_measurement_update'),
     path('units_measurement/<int:pk>/delete/',
          views.UnitsMeasurementDeleteView.as_view(),
          name='units_measurement_delete'),

     # url paths for MocLimit
     path('moc_limit/',
          views.MocLimitListView.as_view(),
          name='moc_limit'),
     path('moc_limit/add/',
          views.MocLimitAddView.as_view(),
          name='moc_limit_add'),
     path('moc_limit/<int:pk>/update/',
          views.MocLimitUpdateView.as_view(),
          name='moc_limit_update'),
     path('moc_limit/<int:pk>/delete/',
          views.MocLimitDeleteView.as_view(),
          name='moc_limit_delete'),

     # url paths for VerificationSign
     path('verification_sign/',
          views.ChangeTypeListView.as_view(),
          name='verification_sign'),
     path('verification_sign/add/',
          views.VerificationSignAddView.as_view(),
          name='verification_sign_add'),
     path('verification_sign/<int:pk>/update/',
          views.VerificationSignUpdateView.as_view(),
          name='verification_sign_update'),
     path('verification_signchange_type/<int:pk>/delete/',
          views.VerificationSignDeleteView.as_view(),
          name='verification_sign_delete'),

     # url paths for RepairDepartment
     path('repair_department/',
          views.RepairDepartmentListView.as_view(),
          name='repair_department'),
     path('repair_department/add/',
          views.RepairDepartmentAddView.as_view(),
          name='repair_department_add'),
     path('repair_department/<int:pk>/update/',
          views.RepairDepartmentUpdateView.as_view(),
          name='repair_department_update'),
     path('repair_department/<int:pk>/delete/',
          views.RepairDepartmentDeleteView.as_view(),
          name='repair_department_delete'),
]
