from .passport import (PassportListView,
                       MocListDetailView,
                       MocListCreateView,
                       MocListUpdateView,
                       MocListDeleteView,
                       PassportMigrateView,
                       PassportPrintView,
                       PassportMocTypeView,
                       PassportChangeTypeView,
                       PassportMocGroupView,
                       PassportVerificationDepartmentView)
from .verification_info import (VerificationInfoCreateView,
                                VerificationInfoDeleteView,
                                VerificationInfoUpdateView,
                                PassportVerificationPersonView,
                                PassportVerificationSignView)
from .repair_info import (RepairInfoCreateView,
                          RepairInfoDeleteView,
                          RepairInfoUpdateView,
                          PassportRepairView,
                          PassportRepairCodeView,
                          PassportRepairDepartmentView,
                          PassportInstrumentFailureView)
from .device_location import (DeviceLocationCreateView,
                              DeviceLocationDeleteView,
                              DeviceLocationUpdateView,
                              PassportDepartmentView)
from .device_status_date import (DeviceStatusDateCreateView,
                                 DeviceStatusDateDeleteView,
                                 DeviceStatusDateUpdateView,
                                 PassportDeviceStatusView)
from .moc_metals import (MocMetalsCreateView,
                         MocMetalsDeleteView,
                         MocMetalsUpdateView,
                         PassportPreciousMetalsView)
