from django.urls import path
from . import views


urlpatterns = [
     # поверки
     path('moc_verification_types/',
          views.MocVerificationTypesView.as_view(),
          name='moc_verification_types'),
     path('moc_in_storage/',
          views.MocInStorageView.as_view(),
          name='moc_in_storage'),
     path('moc_in_use/',
          views.MocInUseView.as_view(),
          name='moc_in_use'),
     path('memorandum/',
          views.MemorandumView.as_view(),
          name='memorandum'),
     path('memorandum_builtin/',
          views.MemorandumBuiltinView.as_view(),
          name='memorandum_builtin'),
     path('prescription/',
          views.PrescriptionView.as_view(),
          name='prescription'),
     path('prescription_builtin/',
          views.PrescriptionBuiltinView.as_view(),
          name='prescription_builtin'),
     path('statement/',
          views.StatementView.as_view(),
          name='statement'),
     path('statement_builtin/',
          views.StatementBuiltinView.as_view(),
          name='statement_builtin'),
     path('moc_presence/',
          views.MocPresenceView.as_view(),
          name='moc_presence'),
     path('moc_presence_builtin/',
          views.MocPresenceBuiltinView.as_view(),
          name='moc_presence_builtin'),
     path('verification_log/',
          views.VerificationLogView.as_view(),
          name='verification_log'),
     path('receipt/',
          views.ReceiptView.as_view(),
          name='receipt'),
     path('moc_indicators/',
          views.MocIndicatorsView.as_view(),
          name='moc_indicators'),
     path('moc_indicators_installed/',
          views.MocIndicatorsInstalledView.as_view(),
          name='moc_indicators_installed'),
     path('completed_works/',
          views.CompletedWorksView.as_view(),
          name='completed_works'),
     path('operating_time/',
          views.OperatingTimeView.as_view(),
          name='operating_time'),
     path('verification_report/',
          views.VerificationReportView.as_view(),
          name='verification_report'),

     # ремонты
     path('repair_log/',
          views.RepairLogView.as_view(),
          name='repair_log'),
     path('repair_long_term/',
          views.RepairLongTermView.as_view(),
          name='repair_long_term'),
     path('repair_operating_time/',
          views.RepairOperatingTimeView.as_view(),
          name='repair_operating_time'),
     path('repair_report/',
          views.RepairReportView.as_view(),
          name='repair_report'),
     path('repair_completed_works/',
          views.RepairCompletedWorksView.as_view(),
          name='repair_completed_works'),
     path('repair_statement/',
          views.RepairStatementView.as_view(),
          name='repair_statement'),
]
