from django.urls import path
from . import views


urlpatterns = [
     path('moc_verification_types/',
          views.MocVerificationTypesView.as_view(),
          name='moc_verification_types'),
     path('moc_in_storage/',
          views.MocInStorageView.as_view(),
          name='moc_in_storage'),
     path('moc_in_use/',
          views.MocInUseView.as_view(),
          name='moc_in_use'),
     path('memorandum/',
          views.MemorandumView.as_view(),
          name='memorandum'),
     path('memorandum_builtin/',
          views.MemorandumBuiltinView.as_view(),
          name='memorandum_builtin'),
     path('prescription/',
          views.PrescriptionView.as_view(),
          name='prescription'),
     path('prescription_builtin/',
          views.PrescriptionBuiltinView.as_view(),
          name='prescription_builtin'),
     path('statement/',
          views.StatementView.as_view(),
          name='statement'),
     path('statement_builtin/',
          views.StatementBuiltinView.as_view(),
          name='statement_builtin'),
     path('moc_presence/',
          views.MocPresenceView.as_view(),
          name='moc_presence'),
     path('moc_presence_builtin/',
          views.MocPresenceBuiltinView.as_view(),
          name='moc_presence_builtin'),
]
