from .moc_group import MocGroupForm
from .change_type import ChangeTypeForm
from .department import DepartmentForm
from .repair import RepairForm
from .precious_metals import PreciousMetalsForm
from .verification_department import VerificationDepartmentForm
from .verification_person import VerificationPersonForm
from .repair_code import RepairCodeForm
from .instrument_failure import InstrumentFailureForm
from .device_status import DeviceStatusForm
from .moc_type import MocTypeForm
from .units_measurement import UnitsMeasurementForm
from .moc_limit import MocLimitForm
from .verification_sign import VerificationSignForm
from .repair_department import RepairDepartmentForm
