from .moc_verification_types import MocVerificationTypesView
from .moc_in_storage import MocInStorageView
from .moc_in_use import MocInUseView
from .memorandum import MemorandumView
from .memorandum_builtin import MemorandumBuiltinView
from .prescription import PrescriptionView
from .prescription_builtin import PrescriptionBuiltinView
from .statement import StatementView
from .statement_builtin import StatementBuiltinView
from .moc_presence import MocPresenceView
from .moc_presence_builtin import MocPresenceBuiltinView
from .verification_log import VerificationLogView
from .receipt import ReceiptView
from .moc_indicators import MocIndicatorsView
from .moc_indicators_installed import MocIndicatorsInstalledView
from .completed_works import CompletedWorksView
from .operating_time import OperatingTimeView
from .verification_report import VerificationReportView
